# HTTP 配置
Http:
  Port: 8080

# 数据库配置
Database:
  Username: root
  Password: Rch~500235
  Name: gorm
  Host: 127.0.0.1:3306
  Prefix:
  Charset: utf8

# 默认管理员
Root:
  Username: admin
  Password: admin
